[workspace]

members = [
"zff",
"zffacquire"
]

[profile.release]
lto = true				# enables link time optimization
panic = 'unwind'		# unwinds the stack if panic
debug = false			# I won't see any debug options in release mode.
opt-level = 'z'  		# optimized for size.
codegen-units = 1		# Set to 1 to allow for maximum size reduction optimizations - at the expense of the compile time.